/*
 * Unified dashboard layer.
 * Keeps all four portal dashboards aligned while feature-page logic stays in app.js.
 * Vantras AI Copilot remains available only on the Student dashboard.
 */

const DASH49 = {
  student:{eyebrow:'Student Learning Portal',title:'Build confidence through consistent learning.',desc:'Continue enrolled courses, review progress, complete assessments and keep your learning evidence in one focused workspace.',art:'managed/hero-student.jpg',primary:['mycourses','Continue Learning','learn'],secondary:['learningpath','Learning Path','results'],highlights:[['courses','Enrolled learning'],['assessment','Assessment readiness'],['certificate','Verified outcomes']],actions:[['browse','search','Browse Courses','Discover new programs'],['mycourses','courses','My Courses','Continue enrolled learning'],['assessments','assessment','Assessments','Practice and submit tests'],['certificates','certificate','Certificates','View earned credentials']]},
  trainer:{eyebrow:'Trainer Workspace',title:'Deliver better learning with clear visibility.',desc:'Manage courses, learners, assessments, sessions and training outcomes from a balanced delivery dashboard.',art:'managed/hero-trainer.jpg',primary:['courses','Manage Courses','courses'],secondary:['reports','View Reports','report'],highlights:[['courses','Course delivery'],['users','Learner progress'],['assessment','Assessment quality']],actions:[['create','plus','Create Course','Build new content'],['learners','users','Learners','Track participation'],['assessments','assessment','Assessments','Manage knowledge checks'],['sessions','live','Live Sessions','Schedule learning']]},
  corporate:{eyebrow:'Corporate Training Portal',title:'Turn workforce learning into measurable progress.',desc:'Assign training, monitor employee progress, manage deadlines and retain completion evidence across your organization.',art:'managed/hero-corporate.jpg',primary:['assignment','Assign Training','learn'],secondary:['reports','View Reports','report'],highlights:[['users','Workforce visibility'],['results','Progress tracking'],['certificate','Training evidence']],actions:[['team','users','My Team','Manage employees'],['assignment','learn','Assign Training','Start learning plans'],['progress','results','Employee Progress','Monitor completion'],['certificates','certificate','Certificates','Review evidence']]},
  admin:{eyebrow:'Administration Portal',title:'Operate the learning platform with confidence.',desc:'Review platform activity, users, catalogue quality, transactions, credentials and operational health from one control centre.',art:'managed/hero-admin.jpg',primary:['users','Manage Users','users'],secondary:['analytics','View Analytics','results'],highlights:[['shield','Platform governance'],['results','Operational visibility'],['report','Audit-ready records']],actions:[['users','users','Users','Manage access'],['approvals','shield','Approvals','Review publishing'],['payments','payment','Payments','Monitor transactions'],['analytics','results','Analytics','Review platform trends']]}
};

function dashboardHeroV49(role){
  const c=DASH49[role]||DASH49.student;
  const first=esc(state.user?.name?.split(' ')[0]||roleLabel(role));
  return `<section class="dash49-hero"><div class="dash49-hero-copy"><div class="dash49-kicker"><span class="eyebrow">${c.eyebrow}</span><span class="dash49-live">Live workspace</span></div><h1>${role==='student'?`Hi ${first}, ${c.title}`:c.title}</h1><p>${c.desc}</p><div class="dash49-highlights">${c.highlights.map(x=>`<span>${icon(x[0])}<b>${x[1]}</b></span>`).join('')}</div><div class="dash49-hero-actions"><button class="btn btn-primary" onclick="openPage('${c.primary[0]}')">${icon(c.primary[2])}${c.primary[1]}</button><button class="btn btn-ghost" onclick="openPage('${c.secondary[0]}')">${icon(c.secondary[2])}${c.secondary[1]}</button></div></div><div class="dash49-hero-media"><img src="assets/${c.art}" alt="${c.eyebrow}"><span>Vantras EHS Academy</span></div></section>`;
}
portalHero=dashboardHeroV49;

/* Dashboard shortcuts intentionally use text + icons; photography stays in the hero. */
dashboardVisualRibbon=function(role){
  const c=DASH49[role]||DASH49.student;
  return `<div class="dash49-actions">${c.actions.map((x,i)=>`<button onclick="openPage('${x[0]}')"><span class="dash49-action-no">0${i+1}</span><span class="dash49-action-icon">${icon(x[1])}</span><span class="dash49-action-copy"><b>${x[2]}</b><small>${x[3]}</small></span><strong>→</strong></button>`).join('')}</div>`;
};

function dash49Metrics(items){return `<div class="dash49-metrics">${items.map(x=>metric(x[0],x[1],x[2],x[3]||'',x[4]||'dashboard',x[5]||'')).join('')}</div>`}
function dash49Card(title,linkLabel,linkAction,body,cls=''){return `<section class="card dash49-card ${cls}">${sectionTitle(title,linkLabel||'',linkAction||'')}${body}</section>`}
function dash49Empty(title,body,actionLabel='',action=''){return `<div class="dash49-empty"><span>${icon('learn')}</span><b>${esc(title)}</b><p>${esc(body)}</p>${actionLabel?`<button class="btn btn-primary btn-sm" onclick="${action}">${esc(actionLabel)}</button>`:''}</div>`}

async function renderStudentDashboardV49(el){
  const [d,my,ass]=await Promise.all([api('/api/dashboard'),api('/api/student/my-courses'),api('/api/student/assessments')]);
  const m=d.metrics,c=my.courses||[],tests=ass.assessments||[];state.myCourses=c;state.assessments=tests;
  const courseRows=c.length?c.map((x,i)=>`<div class="dash49-course"><span class="dash49-index">${String(i+1).padStart(2,'0')}</span><div><div class="kicker">${i===0?'Continue Learning':esc(x.code)}</div><b>${esc(x.title)}</b><small>${esc(x.category||x.level||'Course')} • ${esc(x.duration||'Self-paced')}</small></div><div class="dash49-mini-progress"><b>${x.progress||0}%</b>${progress(x.progress||0)}</div><button class="btn ${i===0?'btn-primary':'btn-ghost'} btn-sm" onclick="state.selectedCourse=${x.id};openPage('courseplayer')">${i===0?'Continue':'Open'}</button></div>`).join(''):dash49Empty('No enrolled courses yet','Enroll in a course to build your learning path.','Browse Courses',"openPage('browse')");
  const ending=[...tests].sort((a,b)=>Number(a.ending_in_days)-Number(b.ending_in_days));
  const testRows=ending.length?ending.map(a=>`<div class="dash49-deadline"><div class="date-badge"><div class="month">${new Date(a.due_date+'T00:00:00').toLocaleDateString('en-IN',{month:'short'}).toUpperCase()}</div><div class="day">${new Date(a.due_date+'T00:00:00').getDate()}</div></div><div><b>${esc(a.title)}</b><small>${esc(a.course)} • ${a.time_minutes} min</small></div><span class="ending-chip ${a.ending_in_days<=3?'urgent':''}">Ends in ${a.ending_in_days} day${a.ending_in_days===1?'':'s'}</span><button class="btn btn-primary btn-sm" onclick="goToAssessment(${a.id})">Open</button></div>`).join(''):dash49Empty('No upcoming deadlines','Your enrolled-course assessments will appear here.');
  el.innerHTML=`${dash49Metrics([['Overall Progress',m.progress+'%','Across enrolled courses','green','results','+8%'],['My Courses',m.enrolled,'Active learning','blue','courses'],['Completed',m.completed,'Courses finished','orange','certificate'],['Assessment Score',m.avg_score+'%','Average result','purple','assessment','+4%'],['Certificates',m.certificates,'Verified credentials','','certificate']])}<div class="dash49-grid">${dash49Card('My Learning Path','View all',"openPage('mycourses')",`<p class="dash49-helper">Two courses stay visible. Scroll inside this card to view the complete learning path.</p><div class="dash49-scroll dash49-learning">${courseRows}</div>`)}${dash49Card('Performance Trend','Detailed analytics',"openPage('performance')",`<div class="dash49-meta"><span class="pill green">Last 7 assessments</span><span>Average ${m.avg_score}%</span></div><div class="dash49-chart">${lineChart([48,56,62,58,70,76,Math.max(78,m.avg_score||78)])}</div>`)}${dash49Card('Progress Overview','','',`<div class="dash49-progress">${ring(m.progress,'Learning')}<div class="hbar-list"><div class="hbar-row"><span>Course Progress</span><div class="hbar-track"><span style="width:${m.progress}%"></span></div><b>${m.progress}%</b></div><div class="hbar-row"><span>Assessments</span><div class="hbar-track"><span style="width:${Math.max(20,m.avg_score)}%"></span></div><b>${m.avg_score}%</b></div><div class="hbar-row"><span>Certificates</span><div class="hbar-track"><span style="width:${Math.min(100,m.certificates*25)}%"></span></div><b>${m.certificates}</b></div></div></div>`)}${dash49Card('Exams Ending Soon','All assessments',"openPage('assessments')",`<p class="dash49-helper">Two exams stay visible. Scroll inside this card to see every deadline.</p><div class="dash49-scroll dash49-exams">${testRows}</div>`)}</div>`;
}

async function renderTrainerDashboardV49(el){
  const [d,c,l]=await Promise.all([api('/api/dashboard'),api('/api/courses'),api('/api/trainer/learners')]);const m=d.metrics,courses=c.courses||[];state.trainerCourses=courses;
  const rows=courses.slice(0,6).map(x=>`<div class="dash49-record"><span class="dash49-row-icon">${icon('courses')}</span><div><b>${esc(x.title)}</b><small>${esc(x.code)} • ${esc(x.level)}</small></div><span class="status ${x.status==='published'?'active':'assigned'}">${esc(x.status)}</span><button class="btn btn-ghost btn-sm" onclick="openPage('courses')">Open</button></div>`).join('')||dash49Empty('No courses assigned','Assigned courses will appear here.');
  const sessions=[['10','Working at Height Q&A','5:00 PM'],['13','Fire Safety Workshop','11:30 AM'],['17','HIRA Case Clinic','6:00 PM']].map(x=>`<div class="dash49-deadline"><div class="date-badge"><div class="month">SEP</div><div class="day">${x[0]}</div></div><div><b>${x[1]}</b><small>${x[2]} • Online</small></div><button class="btn btn-ghost btn-sm" onclick="openPage('sessions')">Manage</button></div>`).join('');
  el.innerHTML=`${dash49Metrics([['Total Courses',m.courses,'Assigned to you','','courses'],['Published',m.published,'Live catalogue','green','shield','+2'],['Learners',m.learners,'Across your courses','blue','users','+18'],['Assessments',m.assessments,'Assessment studio','orange','assessment'],['Question Bank',m.question_bank,'Reusable questions','purple','exam']])}<div class="dash49-grid">${dash49Card('My Recent Courses','Manage courses',"openPage('courses')",`<div class="dash49-scroll dash49-records">${rows}</div>`)}${dash49Card('Learner Performance','All learners',"openPage('learners')",`${lineChart([66,70,72,75,79,82,85])}<div class="hbar-list dash49-bars">${[['Completion',78],['Average Score',85],['Engagement',91]].map(x=>`<div class="hbar-row"><span>${x[0]}</span><div class="hbar-track"><span style="width:${x[1]}%"></span></div><b>${x[1]}%</b></div>`).join('')}</div>`)}${dash49Card('Course Status','Manage courses',"openPage('courses')",`<div class="dash49-status"><div class="donut"><div class="donut-label">${m.courses}<span>Courses</span></div></div><div>${[['status-green','Published','Live and visible',m.published],['status-blue','Draft','In development',m.draft],['status-gray','Archived','Retained for records',m.archived||0]].map(x=>`<div class="dash49-status-row"><i class="${x[0]}"></i><span><b>${x[1]}</b><small>${x[2]}</small></span><strong>${x[3]}</strong></div>`).join('')}</div></div>`)}${dash49Card('Upcoming Live Sessions','All sessions',"openPage('sessions')",`<div class="dash49-scroll dash49-records">${sessions}</div>`)}</div>`;
}

async function renderCorporateDashboardV49(el){
  const [d,e,en]=await Promise.all([api('/api/dashboard'),api('/api/corporate/employees'),api('/api/corporate/enrollments')]);const m=d.metrics,rows=en.enrollments||[];
  const enrollments=rows.slice(0,6).map(x=>`<div class="dash49-record"><span class="dash49-row-icon">${icon('learn')}</span><div><b>${esc(x.employee)}</b><small>${esc(x.course)}</small></div><div class="dash49-mini-progress"><b>${x.progress}%</b>${progress(x.progress)}</div><span class="status ${x.progress>=100?'completed':'assigned'}">${esc(x.status)}</span></div>`).join('')||dash49Empty('No assignments yet','Assigned employee training will appear here.');
  const deadlines=[['12','Fire Safety assessment','8 employees'],['16','HIRA course completion','14 employees'],['20','Work at Height refresher','11 employees']].map(x=>`<div class="dash49-deadline"><div class="date-badge"><div class="month">SEP</div><div class="day">${x[0]}</div></div><div><b>${x[1]}</b><small>${x[2]}</small></div><span class="deadline-chip">Due</span></div>`).join('');
  el.innerHTML=`${dash49Metrics([['Employees',m.employees,'Team directory','','users','+12'],['Enrollments',m.assignments,'Course assignments','blue','learn','+24'],['Completed',m.completed,'Training completed','green','certificate'],['Avg Progress',m.avg_progress+'%','Across assignments','orange','results','+7%'],['Certificates',m.certificates,'Completion evidence','purple','certificate']])}<div class="dash49-grid">${dash49Card('Training Progress','View progress',"openPage('progress')",`<div class="hbar-list dash49-bars">${[['Occupational Safety',86],['Fire & Emergency',78],['Risk Management',71],['Compliance',64],['Environmental',58]].map(x=>`<div class="hbar-row"><span>${x[0]}</span><div class="hbar-track"><span style="width:${x[1]}%"></span></div><b>${x[1]}%</b></div>`).join('')}</div><div class="dash49-chart-compact">${lineChart([48,55,63,68,72,76,Math.max(78,m.avg_progress)])}</div>`)}${dash49Card('Completion Overview','Reports',"openPage('reports')",`<div class="dash49-progress">${ring(m.avg_progress,'Training')}<div class="dash49-summary">${[['Completed',m.completed],['In progress',Math.max(0,m.assignments-m.completed)],['Certified',m.certificates]].map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div></div>`)}${dash49Card('Recent Enrollments','Manage',"openPage('enrollments')",`<div class="dash49-scroll dash49-records">${enrollments}</div>`)}${dash49Card('Upcoming Deadlines','Training plans',"openPage('assignment')",`<div class="dash49-scroll dash49-records">${deadlines}</div>`)}</div>`;
}

async function renderAdminDashboardV49(el){
  const [d,u,pay,cert]=await Promise.all([api('/api/dashboard'),api('/api/admin/users'),api('/api/admin/payments'),api('/api/admin/certificates')]);const m=d.metrics,users=u.users||[],payments=pay.payments||[];
  const userRows=users.slice(-6).reverse().map(x=>`<div class="dash49-record"><span class="dash49-user">${initials(x.name)}</span><div><b>${esc(x.name)}</b><small>${esc(x.email)} • ${esc(x.company||'Independent')}</small></div><span class="pill">${esc(x.role)}</span></div>`).join('')||dash49Empty('No users yet','Registered users will appear here.');
  const tx=payments.slice(0,6).map(x=>`<div class="dash49-record"><span class="dash49-row-icon">${icon('payment')}</span><div><b>${esc(x.student)} • ${money(x.amount)}</b><small>${esc(x.course)} • ${fmtDate(x.paid_at)}</small></div><span class="status successful">${esc(x.status)}</span></div>`).join('')||dash49Empty('No transactions yet','Successful payments will appear here.');
  el.innerHTML=`${dash49Metrics([['Users',m.users,'All platform roles','','users','+8.4%'],['Students',m.students,'Registered learners','blue','learn','+6.1%'],['Courses',m.courses,'Catalogue & drafts','green','courses','+3'],['Revenue',money(m.revenue),`${m.orders} orders`,'orange','payment','+12%'],['Certificates',m.certificates,'Currently valid','purple','certificate']])}<div class="dash49-grid">${dash49Card('Platform Growth','Analytics',"openPage('analytics')",`${lineChart([34,43,49,58,65,76,88])}<div class="dash49-summary horizontal">${[['Learning activity','+18%'],['Revenue trend','+12%'],['Total orders',m.orders]].map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div>`)}${dash49Card('Platform Health','System settings',"openPage('settings')",`<div class="dash49-health">${[['Database','Operational','green'],['Authentication','Operational','green'],['Payments','Webhook-ready','blue'],['Certificates','Verification online','green'],['AI Assistant','Student dashboard enabled','blue']].map(x=>`<div><span class="health-check">✓</span><span><b>${x[0]}</b><small>${x[1]}</small></span><span class="status ${x[2]==='green'?'active':'assigned'}">Online</span></div>`).join('')}</div>`)}${dash49Card('Recent Users','Manage users',"openPage('users')",`<div class="dash49-scroll dash49-records">${userRows}</div>`)}${dash49Card('Recent Transactions','Payments',"openPage('payments')",`<div class="dash49-scroll dash49-records">${tx}</div>`)}</div>`;
}

/* Final dashboard router. Feature pages still use the original portal implementations. */
const _studentPage49=studentPage,_trainerPage49=trainerPage,_corporatePage49=corporatePage,_adminPage49=adminPage;
studentPage=async p=>p==='dashboard'?renderStudentDashboardV49(document.getElementById('portalContent')):_studentPage49(p);
trainerPage=async p=>p==='dashboard'?renderTrainerDashboardV49(document.getElementById('portalContent')):_trainerPage49(p);
corporatePage=async p=>p==='dashboard'?renderCorporateDashboardV49(document.getElementById('portalContent')):_corporatePage49(p);
adminPage=async p=>p==='dashboard'?renderAdminDashboardV49(document.getElementById('portalContent')):_adminPage49(p);

/* Start only after all portal/dashboard overrides are registered. */
boot();
